path: './game/static/galletcity_tiles.png'
tile_width: 8
tile_height: 8

tiles:
  grass: [[7,11]]
#  clay: [[7,10]]
  cobblestone: [[3,16]]
  sidewalk_up: [[4,0]]
  road_up: [[2,0]]
  crosswalk: [[1,1]]

  sidewalk_down: [[4,4]]
  railway: [[6,15],[6,16]]
  tree: [[4,1], [4,2]]
  tower: [[3,13],[3,14]]
  red_house: [[1,6],[1,7]]
  blue_house: [[0,6],[0,7]]
  helicopter_pad: [[1,13],[1,14], [2,13], [2,14]]

